GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2VuYWQiLCJpYXQiOjE2MDY1ODU2NzQsImV4cCI6MTYwNjU4NTcwNH0.VzL7ZsxGlzeHtdGfrn_oZu74E0HzcmVN1UGWyIlCioA

###
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2VuYWQiLCJpYXQiOjE2MDc5MjYzOTYsImV4cCI6MTYwNzkyNjUxNn0.FYMDtcgGruZa2Ac8w4GLQ71jxDyfutLLKggqXCVhPnQ

###
POST  http://localhost:4000/login
Content-Type: application/json

{
    "username": "Senad"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2VuYWQiLCJpYXQiOjE2MDY2MDAxNjQsImV4cCI6MTYwNjYwMDI4NH0.xDE6uRzQdk1f2NDn3Hu3iV6uWAqSmKJTrRjTHpvyRSw"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": 
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2VuYWQiLCJpYXQiOjE2MDc5MjYzOTZ9.LNGUDcjBv9yRtW60txfrpGrRyPJFz0GCrrc9QT5vUzc"
}